### ISSUE TITLE
OSError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by manuperezgo** [pimoroni/bme280-python#36]
Hi,

I am new to working with these kind of sensors and not very experienced with python, so my apologies before hand if I am asking something silly.

I have gone through open and closed issues trying to find information on WHY I am getting this error but have not been lucky on finding any answers, so I am raising an issue here.

I am running python virtual envs where the virtual env configuration and `bin` folder is placed next to the script like the following:
![Screenshot 2024-10-29 at 08 14 34](https://github.com/user-attachments/assets/d966497e-3194-454e-996e-e0c532d79689)

As you can see, I am trying to run the examples on this repo, and I am trying to do that like this:

`./bin/python all-values.py`
or
`./bin/python3 all-values.py`

In both cases I get the following error:

```
all-values.py - Read temperature, pressure, and humidity

Press Ctrl+C to exit!


Traceback (most recent call last):
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/bme280/__init__.py", line 215, in setup
    chip = self._bme280.get("CHIP_ID")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/i2cdevice/__init__.py", line 230, in get
    self.read_register(register)
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/i2cdevice/__init__.py", line 183, in read_register
    self.values[register.name] = self._i2c_read(register.address, register.bit_width)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/i2cdevice/__init__.py", line 288, in _i2c_read
    for x in self._i2c.read_i2c_block_data(self._i2c_address, register, bit_width // self._bit_width):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/smbus2/smbus2.py", line 619, in read_i2c_block_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manupgz/Projects/python/bme280-python/examples/all-values.py", line 22, in <module>
    temperature = bme280.get_temperature()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/bme280/__init__.py", line 248, in get_temperature
    self.update_sensor()
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/bme280/__init__.py", line 234, in update_sensor
    self.setup()
  File "/home/manupgz/Projects/python/bme280-python/examples/lib/python3.11/site-packages/bme280/__init__.py", line 219, in setup
    raise RuntimeError("Unable to find bme280 on 0x{:02x}, IOError".format(self._i2c_addr))
RuntimeError: Unable to find bme280 on 0x76, IOError
```

The device seems to be detected correctly:
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --
```

and it is connected to the PI by following this diagram:
<img width="864" alt="Screenshot 2024-10-29 at 08 25 13" src="https://github.com/user-attachments/assets/5930b324-aaed-411e-a053-a2a519ef627e">
although I am using a Pi5

And the bme280 library being used seems to be the right one:

```
$ ./bin/pip freeze | grep bme280
pimoroni-bme280==1.0.0
```
or:
```
$ ./bin/pip3 freeze | grep bme280
pimoroni-bme280==1.0.0
```

I have tried the above by instaling the library via the script and via manually installing on an venv.
```
$ cat /etc/issue
Debian GNU/Linux 12 \n \l
```

Any advice will be highly appreciated.

Many thanks

**Comment by manuperezgo** [comment]
Forgot to say before, this was also run:

`sudo raspi-config nonint do_i2c 0`

**Comment by Gadgetoid** [comment]
Ahoy!

Sorry for the delay responding to such a thoroughly detailed issue. Appreciate the effort you put in here. Did you figure it out?

**Comment by manuperezgo** [comment]
hi @Gadgetoid yes I did, it was an issue with the virtualenvs

By running the install script the virtual env was being created but it was not activating so the dependancy was not resolving (or something like that).
